#!/bin/bash

# StockENT Environment Setup Script
# Interactive setup for environment variables

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

print_header() {
    echo ""
    echo -e "${CYAN}╔════════════════════════════════════════════════════════════╗${NC}"
    echo -e "${CYAN}║${NC}          ${BLUE}StockENT Environment Setup${NC}                        ${CYAN}║${NC}"
    echo -e "${CYAN}╚════════════════════════════════════════════════════════════╝${NC}"
    echo ""
}

print_status() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

print_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

print_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Generate random string for secrets
generate_secret() {
    openssl rand -hex 32
}

print_header

# Check if .env files already exist
if [ -f "backend/.env" ]; then
    echo -e "${YELLOW}Existing backend/.env found.${NC}"
    read -p "Do you want to overwrite it? (y/N): " overwrite_backend
    if [[ ! "$overwrite_backend" =~ ^[Yy]$ ]]; then
        print_warning "Keeping existing backend/.env"
        SKIP_BACKEND=true
    fi
fi

if [ -f "frontend/.env" ]; then
    echo -e "${YELLOW}Existing frontend/.env found.${NC}"
    read -p "Do you want to overwrite it? (y/N): " overwrite_frontend
    if [[ ! "$overwrite_frontend" =~ ^[Yy]$ ]]; then
        print_warning "Keeping existing frontend/.env"
        SKIP_FRONTEND=true
    fi
fi

# Backend Environment Setup
if [ "$SKIP_BACKEND" != "true" ]; then
    print_status "Setting up backend environment..."

    # Generate JWT secrets
    JWT_SECRET=$(generate_secret)
    JWT_REFRESH_SECRET=$(generate_secret)

    # Create backend .env
    cat > backend/.env << EOF
# StockENT Backend Environment
# Generated by setup.sh on $(date)

# Server Configuration
PORT=5001
NODE_ENV=development

# Database (Docker Compose)
DATABASE_URL="postgresql://devuser:devpass@localhost:5432/stockent_db?schema=public"

# Redis (Docker Compose)
REDIS_URL="redis://localhost:6379"

# JWT Authentication
JWT_SECRET=$JWT_SECRET
JWT_REFRESH_SECRET=$JWT_REFRESH_SECRET
JWT_EXPIRES_IN=7d
JWT_REFRESH_EXPIRES_IN=30d

# CORS
FRONTEND_URL=http://localhost:3000

# Email (configure for production)
SMTP_HOST=smtp.mailtrap.io
SMTP_PORT=2525
SMTP_USER=
SMTP_PASS=
EMAIL_FROM=noreply@stockent.com

# Google OAuth (optional)
GOOGLE_CLIENT_ID=
GOOGLE_CLIENT_SECRET=
GOOGLE_CALLBACK_URL=http://localhost:5001/api/auth/google/callback

# File Upload
MAX_FILE_SIZE=10485760
UPLOAD_PATH=./uploads

# Admin Credentials
ADMIN_EMAIL=admin@stockent.com
ADMIN_PASSWORD=admin123

# Encryption (for messaging)
ENCRYPTION_KEY=$(generate_secret)
EOF

    print_success "Backend .env created"
fi

# Frontend Environment Setup
if [ "$SKIP_FRONTEND" != "true" ]; then
    print_status "Setting up frontend environment..."

    cat > frontend/.env << EOF
# StockENT Frontend Environment
# Generated by setup.sh on $(date)

# API Configuration
NEXT_PUBLIC_API_URL=http://localhost:5001/api
NEXT_PUBLIC_SOCKET_URL=http://localhost:5001

# App Configuration
NEXT_PUBLIC_APP_NAME=StockENT
NEXT_PUBLIC_APP_VERSION=1.0.0
NEXT_PUBLIC_ENVIRONMENT=development
EOF

    print_success "Frontend .env created"
fi

# Root .env for Taskfile
print_status "Creating root .env for Taskfile..."
cat > .env << EOF
# StockENT Root Environment
# Used by Taskfile.yml

# Development Ports
BACKEND_PORT=5001
FRONTEND_PORT=3000

# Database Configuration
DB_USER=devuser
DB_PASS=devpass
DB_NAME=stockent_db
EOF

print_success "Root .env created"

echo ""
echo -e "${GREEN}╔════════════════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║${NC}              ${GREEN}Setup Complete!${NC}                               ${GREEN}║${NC}"
echo -e "${GREEN}╚════════════════════════════════════════════════════════════╝${NC}"
echo ""
echo -e "Next steps:"
echo -e "  1. ${CYAN}task docker:start${NC}  - Start PostgreSQL and Redis"
echo -e "  2. ${CYAN}task install${NC}       - Install dependencies"
echo -e "  3. ${CYAN}task db:migrate${NC}    - Run database migrations"
echo -e "  4. ${CYAN}task db:seed${NC}       - Seed sample data"
echo -e "  5. ${CYAN}task local${NC}         - Start development servers"
echo ""
echo -e "Or run everything at once with: ${CYAN}task setup${NC}"
echo ""
